apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: job-portal
data:
  DB_HOST: "db"
  DB_PORT: "5432"
  DB_NAME: "jobportal"
  PORT: "5000"
  NODE_ENV: "production"
  UPLOADS_PATH: "/usr/src/app/uploads"
  ALLOWED_ORIGIN: "http://localhost" # Or the external URL if needed, but relative proxy handles this
